//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaOcaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Amistades
    {
        public int idAmistad { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> idJugadorSolicitante { get; set; }
        public Nullable<int> idJugadorReceptor { get; set; }
    
        public virtual Jugadores Jugadores { get; set; }
        public virtual Jugadores Jugadores1 { get; set; }
    }
}
