//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaOcaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresAspectos
    {
        public int IdJugadorAspecto { get; set; }
        public Nullable<int> IdJugador { get; set; }
        public Nullable<int> IdAspecto { get; set; }
    
        public virtual Aspectos Aspectos { get; set; }
        public virtual Jugadores Jugadores { get; set; }
    }
}
