//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaOcaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class JugadoresAspectos
    {
        public int idJugadorAspecto { get; set; }
        public Nullable<int> idJugador { get; set; }
        public Nullable<int> idAspecto { get; set; }
    
        public virtual Aspectos Aspectos { get; set; }
        public virtual Jugadores Jugadores { get; set; }
    }
}
