//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaOcaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jugadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jugadores()
        {
            this.Amistades = new HashSet<Amistades>();
            this.Amistades1 = new HashSet<Amistades>();
            this.JugadoresAspectos = new HashSet<JugadoresAspectos>();
        }
    
        public int idJugador { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<int> idPuntuacion { get; set; }
        public Nullable<int> idFotoPerfil { get; set; }
        public Nullable<int> idCuenta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Amistades> Amistades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Amistades> Amistades1 { get; set; }
        public virtual Aspectos Aspectos { get; set; }
        public virtual Cuentas Cuentas { get; set; }
        public virtual Puntuaciones Puntuaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JugadoresAspectos> JugadoresAspectos { get; set; }
    }
}
