//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaOcaDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Puntuaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Puntuaciones()
        {
            this.Jugadores = new HashSet<Jugadores>();
        }
    
        public int IdPuntuacion { get; set; }
        public Nullable<int> casillasRecorridasGlobal { get; set; }
        public Nullable<int> monedasObtenidasGlobal { get; set; }
        public Nullable<int> partidasGanadasGlobal { get; set; }
        public Nullable<int> monedasActuales { get; set; }
        public Nullable<int> IdJugador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Jugadores> Jugadores { get; set; }
    }
}
